Init APP automatically generates the default module association confi…
cleey/phppoem pull request #99
Opened 2022-09-07 03:14 UTC by fsd-lsh

…guration

问题描述：
在`phppoem/config.php`下修改 'default_module' => 'admin'，希望默认模块为admin。
请求/admin/xxxx/xxxx会自动生成 home模块。

修复：
`phppoem/core/app.php` ::start()中增加判断 `config('default_module')`

2022-09-29 10:36 UTC, devtoolman requested changes

2022-09-29 10:36 UTC, devtoolman commented on phppoem/core/app.php
> +        $module = defined('NEW_MODULE') ? NEW_MODULE : (config('default_module') ? : 'home');
可以直接替换 'home' => config('default_module')

2022-09-29 10:52 UTC, cleey requested changes

2022-09-29 10:52 UTC, cleey commented on phppoem/core/app.php
> +        $module = defined('NEW_MODULE') ? NEW_MODULE : (config('default_module') ? : 'home');
可直接  'home' 替换为 config('default_module') ？

2022-09-30 01:09 UTC, fsd-lsh commented on phppoem/core/app.php
> +        $module = defined('NEW_MODULE') ? NEW_MODULE : (config('default_module') ? : 'home');
已重新提交

2022-10-10 08:44 UTC, merged